### ISSUE TITLE
Too many json files

### ISSUE THREAD

**Issue by daniel03c1** [IRIS-AUDIO/SELD#43]
지금 Json 파일이 너무 많고, 테스트용 json 파일도 너무 많은거 같은데 
baseline처럼 어느정도 고정된 모델이나, 진행하고 있는 중요한 파일 위주로 한번 정리를 하면 어떨지 싶습니다.

**Comment by lsg1213** [comment]
일단 재실험 할 때 필요한 json이 대부분이라 풀리 accept 되면 나중에 진행할게요
