### ISSUE TITLE
model을 언제 학습 중지할지 결정하는 방법론 정하고 구현

### ISSUE THREAD

**Issue by daniel03c1** [IRIS-AUDIO/SELD#48]
많은 랜덤한 모델들의 수치를 구하기 위해서 빠르게 학습이 끝날 수 있도록

의견) 다양한 metric의 수치를 구할필요 없이 일정 epoch동안 학습 진행하고 마지막에 metric한번 하는 것
다른 의견들을 comment 달아서 같이 논의해봐요

**Comment by lsg1213** [comment]
고정된 epoch로 하기로 결정
