### ISSUE TITLE
README가 필요합니다.

### ISSUE THREAD

**Issue by daniel03c1** [IRIS-AUDIO/SELD#52]
현재 README가 없어 어떻게 돌려야하는지 가이드라인이 없습니다.

**Comment by ParkJinHyeock** [comment]
음 정말 간단하게 train.py 돌리는 것까지 필요한것이라면 제가 아예처음부터 했어서 작성할 수 있을 것 같아요. requirements.txt 까지는 작성할 수 있을 것 같네요

**Comment by daniel03c1** [comment]
> 음 정말 간단하게 train.py 돌리는 것까지 필요한것이라면 제가 아예처음부터 했어서 작성할 수 있을 것 같아요. requirements.txt 까지는 작성할 수 있을 것 같네요

오 그러면 오히려 감사하죠! 작성하시면 같이 공유주세요! 감사합니다
